name: prctr-hsa-hw12

services:
  redis1:
    image: redis:latest
    container_name: redis1
    ports:
      - "6379:6379"
    volumes:
      - ./redis1/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - my_network

  redis2:
    image: redis:latest
    container_name: redis2
    ports:
      - "6380:6379"
    volumes:
      - ./redis2/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # RabbitMQ Management Plugin port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - my_network


  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local1:redis1:6379,local2:redis2:6379
    depends_on: 
      - redis1
      - redis2
    networks:
      - my_network

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis1
      - redis2
    networks:
      - my_network

  load-test:
    build: ./load-test
    volumes:
      - ./load-test:/workspace
    depends_on:
      - redis1
      - redis2
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
