name: hsa13-hw12


services:
  redis-master:
    image: redis:latest
    container_name: redis_master
    volumes:
      - ./redis-master/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"

  redis-slave:
    image: redis:latest
    container_name: redis_slave
    volumes:
      - ./redis-slave/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--slaveof", "redis-master", "6379"]
    ports:
      - "6380:6379"
    depends_on:
      - redis-master

  app:
    build: ./loadtest_fastapi
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis-master
      - redis-slave

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # RabbitMQ Management Plugin port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - my_network


  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local1:redis_master:6379,local2:redis_slave:6379
    depends_on: 
      - redis-master
      - redis-slave
    networks:
      - my_network



  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis-master
      - redis-slave
    networks:
      - my_network


  load-tester:
    build:
      context: ./load-test
      dockerfile: Dockerfile.loadtest
    container_name: load_tester
    depends_on:
      - redis-master
      - redis-slave
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
