# Dockerfile.loadtest
FROM alpine:latest

RUN apk add --no-cache redis

COPY ./load-test /load-test



WORKDIR /load-test

RUN chmod +x load_test_redis_rdb.sh
# CMD ["sh", "-c", "./load_test_redis_rdb.sh"]

CMD ["sh", "-c", "./load_test_redis_rdb.sh && ./load_test_redis_aof.sh"]
